# Numpy Overview

**This tutorial gives a quick overview of the numpy arrays and its features**<br>
> - **Importing numpy library**<br>
> - **Creating arrays and initializing**<br>
> - **Reading arrays from files**<br>
> - **Special initializing functions**<br>
> - **Slicing and indexing**<br>
> - **reshaping arrays**<br>
> - **Numpy Maths**<br>
> - **Combining arrays**<br>
> - **Basic algebraic operations using numpy arrays**<br>
> - **Solving linear equations**<br>
> - **Matix inversions**<br>
> - **Calculating eigen vectors**<br>

# Importing numpy library

In [41]:
from numpy import * 

In [3]:
import numpy as np

In [3]:
print dir(np),

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__config__', '__doc__', '__file__', '__git_revision__', '__name__', '__package__', '__path__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc

In [4]:
np.ndarray(range(1,10), dtype='float')

array([[[[[[[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             ...

# Creating one dimensional numpy arrays and initializing

In [7]:
arr_1 = np.array([[1,2,4], [2,3,4], [1,2,10.]])
print arr_1
arr_1.dtype

[[  1.   2.   4.]
 [  2.   3.   4.]
 [  1.   2.  10.]]


dtype('float64')

In [8]:
arr_1[2,2]

10.0

In [9]:
arr_1[2,:]

array([  1.,   2.,  10.])

In [10]:
arr_1[:,0]

array([ 1.,  2.,  1.])

In [11]:





arr_1[1,1:3]

array([ 3.,  4.])

In [12]:
print arr_1[2,0:2]

[ 1.  2.]


In [13]:

range(1,10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
arr_1.dtype

dtype('float64')

In [16]:
type(arr_1)

numpy.ndarray

In [26]:
arr_1

array([[  1.,   2.,   4.],
       [  2.,   3.,   4.],
       [  1.,   2.,  10.]])

In [19]:
arr_1.shape

(3, 3)

In [20]:
arr_1.size

9

In [21]:
arr_1.trace()

14.0

In [22]:
arr_1.sum()

29.0

In [23]:

arr_1.mean()

3.2222222222222223

In [24]:
arr_1.nbytes

72

In [25]:
arr_1.sort()
arr_1

array([[  1.,   2.,   4.],
       [  2.,   3.,   4.],
       [  1.,   2.,  10.]])

In [62]:
print dir(arr_1),

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__hex__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rls

In [27]:
arr_1.ndim

2

In [28]:
a1 = np.array([1,2,20,10])

In [29]:
a1.ndim

1

In [31]:
arr_1.std()

2.6152449546532934

In [33]:
arr_1.dtype

dtype('float64')

In [34]:
## Create one dimensional array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [35]:
## Find the typbe of the object
type(a)

numpy.ndarray


# Numpy Arrays - dtypes & shapes

In [36]:
## Find the dimension of the array
a.shape

(3,)

In [37]:

a.dtype

dtype('int64')

In [38]:
print( a[1] )

2



# Creating two dimensional numpy arrays and initializing

In [41]:
# Create a two dimensional array
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print( b )

[[1 2 3]
 [4 5 6]]


In [42]:
print( b.shape )

(2, 3)


In [43]:
print( b[0, :] )

[1 2 3]


In [44]:

print( b[:, 1] )

[2 5]


In [45]:


b

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:

b[:]

array([[1, 2, 3],
       [4, 5, 6]])

# Reading an array from a file


### narray.txt
>2,4,6,7 <br>
>1,2,3,5 <br>
>3,2,7,8 <br>
>1,5,6,4 <br>

In [ ]:
np.lo

In [79]:
f = np.loadtxt("../Data/", delimiter=',')

IOError: [Errno 21] Is a directory: '../Data/'

In [48]:
np.load?

In [49]:
f

NameError: name 'f' is not defined

In [82]:
f = np.loadtxt("../Data/narray.txt", delimiter=',', dtype = "int")

IOError: [Errno 2] No such file or directory: 'C:\\Users\\ChandraMouli\\Desktop\\narray.txt'

In [83]:
f

NameError: name 'f' is not defined

In [84]:
f.dtype

NameError: name 'f' is not defined

# Special Initializing functions

>zeros, ones, eye, full, random, diag

In [50]:
a = np.zeros((3,3))  # Create an array of all zeros
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [51]:
b = np.ones((5,2)) # Create an array of all ones
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [52]:
d = np.eye(3)
d

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [53]:





d

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [54]:



c = np.full((2,2), 7)

In [55]:
c

array([[7, 7],
       [7, 7]])

In [56]:

e = np.random.random((2,2) )

In [57]:
e

array([[ 0.31283529,  0.80331544],
       [ 0.48645651,  0.941062  ]])

In [58]:


f = np.random.randint(100, size = (4,4) )

In [59]:
f

array([[39, 53,  2, 57],
       [ 0, 69,  8, 79],
       [98, 59, 83, 54],
       [96, 33, 27, 75]])



# Slicing & Indexing an array 

In [60]:
# Get first row
f[0,:]

array([39, 53,  2, 57])

In [61]:


# Get 1 and 2 row
f[0:2,:]

array([[39, 53,  2, 57],
       [ 0, 69,  8, 79]])

In [62]:
f[:, 1]

array([53, 69, 59, 33])

In [63]:

# Get first column
f[:,0]

array([39,  0, 98, 96])

In [64]:

f[:,0:2]

array([[39, 53],
       [ 0, 69],
       [98, 59],
       [96, 33]])

In [65]:
## slicing an array 
## All 
b = f[:2, 1:3]

In [66]:

b

array([[53,  2],
       [69,  8]])

In [67]:


## Get specific elements
np.array([f[0,1], f[2,2]])

array([53, 83])

In [68]:
arr_1>=3

array([[False, False,  True],
       [False,  True,  True],
       [False, False,  True]], dtype=bool)

In [69]:

arr_1

array([[  1.,   2.,   4.],
       [  2.,   3.,   4.],
       [  1.,   2.,  10.]])

In [70]:

arr_1[arr_1>=3]

array([  4.,   3.,   4.,  10.])

In [71]:


## Boolean indexing
f>80

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]], dtype=bool)

In [72]:

arr_2 = np.array([range(0,10), range(10,20), range(20,30)])
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [108]:
arr_2[arr_2>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [109]:
arr_2.shape

(3, 10)

In [110]:
d=np.reshape(arr_2, (5,6))

In [111]:


d[4,:]=0

In [112]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  0,  0,  0,  0,  0]])

In [113]:
g = f[f>80]

In [114]:

g

array([82, 97, 82, 88])

# Reshaping an array

In [115]:


k = np.reshape( f, ( 8,2 ) )

In [116]:

arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]])

In [117]:
np.reshape(arr_1, (1,9))

array([[ 1,  2,  4,  2,  3,  4,  1,  2, 10]])

In [118]:


k

array([[16, 13],
       [56, 26],
       [67, 82],
       [ 4, 97],
       [34,  2],
       [32, 82],
       [78, 37],
       [33, 88]])


# Updating an array

In [119]:
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]])

In [120]:

arr_1[arr_1>=3]=10

In [121]:














arr_1

array([[ 1,  2, 10],
       [ 2, 10, 10],
       [ 1,  2, 10]])

In [122]:
k[7,1] = 0

In [123]:


k

array([[16, 13],
       [56, 26],
       [67, 82],
       [ 4, 97],
       [34,  2],
       [32, 82],
       [78, 37],
       [33,  0]])

In [124]:
k[5:] = 0

In [125]:


k

array([[16, 13],
       [56, 26],
       [67, 82],
       [ 4, 97],
       [34,  2],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

# NUMPY Maths
## Adding, subtracting, multiplying, transposing arryas

In [126]:
x = np.random.randint( 100, size = (5,5) )
y = np.random.randint( 100, size = (5,5) )

In [127]:
x

array([[37, 92, 61, 29, 31],
       [44, 87, 22, 58, 14],
       [13, 60, 11, 68,  9],
       [17, 77, 83, 55, 50],
       [ 2, 93, 75, 21, 41]])

In [128]:
y

array([[47, 85, 57, 32, 39],
       [45, 74, 87, 65, 90],
       [97, 81, 42, 74, 74],
       [99, 15,  2, 90, 82],
       [73, 29, 36, 15, 80]])

In [1]:
## Add two matrices x + y or np.add( x, y )
x + y

NameError: name 'x' is not defined

In [130]:
np.add( x, y )

array([[ 84, 177, 118,  61,  70],
       [ 89, 161, 109, 123, 104],
       [110, 141,  53, 142,  83],
       [116,  92,  85, 145, 132],
       [ 75, 122, 111,  36, 121]])

In [131]:









# np.substract( x, y )
x - y

array([[-10,   7,   4,  -3,  -8],
       [ -1,  13, -65,  -7, -76],
       [-84, -21, -31,  -6, -65],
       [-82,  62,  81, -35, -32],
       [-71,  64,  39,   6, -39]])

In [132]:
# np.multiply( x, y )
x * y

array([[1739, 7820, 3477,  928, 1209],
       [1980, 6438, 1914, 3770, 1260],
       [1261, 4860,  462, 5032,  666],
       [1683, 1155,  166, 4950, 4100],
       [ 146, 2697, 2700,  315, 3280]])

In [133]:
# Matrix Transpose
x.T

array([[37, 44, 13, 17,  2],
       [92, 87, 60, 77, 93],
       [61, 22, 11, 83, 75],
       [29, 58, 68, 55, 21],
       [31, 14,  9, 50, 41]])

# Calculating column sums and row sums

In [134]:
x = np.random.randint( 10, size = (4,4) )

In [135]:
x

array([[0, 7, 0, 2],
       [4, 9, 2, 0],
       [0, 4, 6, 8],
       [6, 1, 2, 9]])

In [136]:
print x.sum(), x.mean(), x.std()

60 3.75 3.23071199583


In [137]:
np.sum(x, axis=0)

array([10, 21, 10, 19])

In [138]:
x+[10,15,20,30]

array([[10, 22, 20, 32],
       [14, 24, 22, 30],
       [10, 19, 26, 38],
       [16, 16, 22, 39]])

In [139]:
l=np.array([[10,20], [20,30]])

In [140]:
l+10

array([[20, 30],
       [30, 40]])

In [141]:
x

array([[0, 7, 0, 2],
       [4, 9, 2, 0],
       [0, 4, 6, 8],
       [6, 1, 2, 9]])

In [142]:
np.std(x)

3.2307119958300214

In [143]:
np.sum( x, axis = 0 )

array([10, 21, 10, 19])

In [144]:
np.sum( x, axis = 1 )

array([ 9, 15, 18, 18])

In [145]:
np.mean( x, axis = 0 )

array([ 2.5 ,  5.25,  2.5 ,  4.75])

In [146]:
np.mean( x, axis = 1 )

array([ 2.25,  3.75,  4.5 ,  4.5 ])

# Combine Arrays 

In [147]:
x = np.random.randint( 10, size = (2,2) )
y = np.random.randint( 100, size = (2,2) )

In [148]:
x

array([[1, 2],
       [5, 2]])

In [149]:
y

array([[58,  5],
       [85, 22]])

In [150]:
np.vstack( [x, y])

array([[ 1,  2],
       [ 5,  2],
       [58,  5],
       [85, 22]])

In [151]:
np.hstack([x, y])

array([[ 1,  2, 58,  5],
       [ 5,  2, 85, 22]])

# Linear Algebra.. Advanced Matrix Operation

In [152]:
from numpy import linalg
import numpy as np

# Solving a set of linear equations 
> 2x + 2y+3z = 5 <br>
> 3x + y +4z = 7 <br>
> 4x + 3y =10

In [153]:
a = np.array([[2,2,3], [3,1,4],[4,3,0]])
b = np.array([5,7,10])
x = np.linalg.solve(a, b)
x

array([ 2.30434783,  0.26086957, -0.04347826])

# Matrix Inversion

In [154]:
a = np.array([[1, 2], [3, 4]])
np.linalg.inv( a )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Calculating an eigen value and vector for a matrix

In [5]:

m1 = np.diag((1, 2, 3))
m1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
eigval, eigvec = np.linalg.eig( m1 )

In [7]:
eigval

array([ 1.,  2.,  3.])

In [8]:
eigvec

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
np.strides?

Object `np.strides` not found.
